### ISSUE TITLE
use `prompt` form pyvenv.cfg as name for `venv`

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/python-environment-tools#191]
![Image](https://github.com/user-attachments/assets/6ab7f1d5-32ca-408d-869b-acc1ae954724)

`pyvenv.cfg` can have a `prompt` field which is the name of the environment used in shell prompts when it is activated. we should read that and use that as the name of the virtual environment, when present. Otherwise use the name of directory where `pyvenv.cfg` is present.

**Comment by DonJayamanne** [comment]
Fixed via https://github.com/microsoft/python-environment-tools/pull/199

**Comment by karthiknadig** [comment]
This is not addressed in the above PR.

**Comment by notuntoward** [comment]
I'm running vscode 1.99.3 and python extension 2025.5.2025041801 and the prompt variable is still not being used in vscode.  But it does show up correctly in my windows terminal
